#!/bin/sh

### BEGIN INIT INFO
# Provides:        Repetier-Server
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: Init script for Repetier-Server
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

DAEMON=/usr/local/Repetier-Server/bin/RepetierServer
CONFIGFILE="/usr/local/Repetier-Server/etc/RepetierServer.xml"
SERVER_OPTS="-c $CONFIGFILE --daemon"
export LC_ALL=C

test -x $DAEMON || exit 5


LOCKFILE=/var/lock/RepetierServer

lock_RepetierServer() {
	if [ -x /usr/bin/lockfile-create ]; then
		lockfile-create $LOCKFILE
		lockfile-touch $LOCKFILE &
		LOCKTOUCHPID="$!"
	fi
}

unlock_RepetierServer() {
	if [ -x /usr/bin/lockfile-create ] ; then
		kill $LOCKTOUCHPID
		lockfile-remove $LOCKFILE
	fi
}

RUNASUSER=root
userid=$(getent | cut -f 3 -d:) || true

case $1 in
	start)
		log_daemon_msg "Starting Repetier-Server" "rsd"
		if [ -z "$userid" ]; then
			log_failure_msg "user \"$RUNASUSER\" does not exist"
			exit 1
		fi
		mkdir -p /var/lib/Repetier-Server
        chown -R repetierserver /var/lib/Repetier-Server
		lock_RepetierServer
  		start-stop-daemon --start --quiet --oknodo -c $RUNASUSER:dialout --startas $DAEMON --exec $DAEMON -- $SERVER_OPTS
		status=$?
		unlock_RepetierServer
		log_end_msg $status
  		;;
	stop)
		log_daemon_msg "Stopping Repetier-Server" "rsd"
  		start-stop-daemon --stop --quiet --oknodo --exec $DAEMON
		log_end_msg $?
  		;;
	restart|force-reload)
		$0 stop && sleep 2 && $0 start
  		;;
	try-restart)
		if $0 status >/dev/null; then
			$0 restart
		else
			exit 0
		fi
		;;
	reload)
		exit 3
		;;
	status)
		status_of_proc $DAEMON "Repetier-Server"
		;;
	*)
		echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
		exit 2
		;;
esac
